services:
  app:
    image: $APP_IMAGE
    hostname: "$APP_NAME.$BASE_DOMAIN"
    networks:
      - dev
    environment:
      - "ELASTICSEARCH_URL=http://elastic.$BASE_DOMAIN:9200"
      - "ELASTICSEARCH_HOSTS=http://elastic.$BASE_DOMAIN:9200"
      - "XPACK_GRAPH_ENABLED=false"
      - "XPACK_ML_ENABLED=false"
      - "XPACK_REPORTING_ENABLED=false"
      - "XPACK_WATCHER_ENABLED=false"
      - "VIRTUAL_HOST=$APP_NAME.$BASE_DOMAIN"
      - "VIRTUAL_PORT=5601"

networks:
  dev:
    external: true
    name: $NETWORK